// Generated by CoffeeScript 1.10.0

/*
 * Assignment:
number   = 42
opposite = true

 * Conditions:
number = -42 if opposite

 * Functions:
square = (x) -> x * x

 * Arrays:
list = [1, 2, 3, 4, 5]

 * Objects:
math =
  root:   Math.sqrt
  square: square
  cube:   (x) -> x * square x

 * Splats:
race = (winner, runners...) ->
  print winner, runners

 * Existence:
alert "I knew it!" if elvis?

 * Array comprehensions:
cubes = (math.cube num for num in list)
 */

(function() {
  var person, square;

  square = function(x) {
    return x * x;
  };

  person = {
    name: {
      first: "anubhav",
      last: "shrimal"
    }
  };

  console.log(person);

  console.log(square(2));

}).call(this);

//# sourceMappingURL=index.js.map
